var language = {
    german: {
        ageQuestion: "Wie alt bist du?",
        typeQuestion: "Welche Art von Fragen möchtest du lösen?",
        moduleQuestion: "Welches Modul möchtest du spielen?",
        wantToPlay: "Oh Hallo! Mächtest du mit mir spielen?",
        startInstruction: "Um zu starten berühre den Bildschirm",
        endOfQuiz: "Oh wir sind schon am Ende dieses Quiz!",
        greatJob: "Super gemacht ",
        wellDone: "Gut gemacht ",
        youHave: "Du hast ",
        from: " von ",
        anweredQuestions: " Fragen richtig gelöst ",
        anwerdQuestionsPerfect: " Fragen richtig gelöst, Klasse!",
        answeredQuestionsNotBad: " Fragen richtig gelöst, nicht schlecht!",
        needToTrain: ", du musst noch ein bisschen üben!",
        talkWithNutritionist: ", gerne kannst du deine Unklarheiten mit unserer Ernährungsberaterin besprechen!",
        errorSpeechFailedCorrectAnswer: "Speech bei richtiger Antwort fehlgeschlagen",
        errorCallEventFailedCorrectAnswer: "Event aufrufen bei richtiger Antwort fehlgeschlagen",
        errorSpeechFailedWrongAnswer: "Speech bei falscher Antwort fehlgeschlagen",
        errorCallEventFailedWrongAnswer: "Event aufrufen bei falscher Antwort fehlgeschlagen",
        errorSpeechFailedAtEnd: "Speech bei Ende fehlgeschlagen",
        errorAddingDatasetToHighscoreWhenExisting: "Hinzufuegen von Datensatz zu Highscore fehlgeschlagen (Wenn andere Datensaetze vorhanden).",
        errorAddingDatasetToHighscore: "Hinzufuegen von Datensatz zu Highscore fehlgeschlagen (wenn andere Datensaetze nicht vorhanden).",
        errorLoadingData: "Fehler beim Laden der Daten",
        enterName: "Gib bitte deinen Namen in das untere Feld ein",
        enterValidName: "Gib bitte einen gültigen Namen ein",
        selectAge: "Wählen Sie das Alter",
        selectCategory: "Wählen Sie das Modul",
        resultForAge: "Resultat für Alter '",
        andModule: "' und Modul '",
        average: "Durchschnitt: ",
        median: "Median: ",
        notAvailable: "Nicht Verfügbar",
        selectType: "Selektieren Sie den Fragetyp"
    },
    english: {
        ageQuestion: "How old are you?",
        typeQuestion: "What kind of questions do you want to solve?",
        moduleQuestion: "Which module do you want to play?",
        wantToPlay: "Oh hello! Would you like to play with me?",
        startInstruction: "Cool, here we go!...To start touch the screen",
        endOfQuiz: "Oh we are already at the end of this quiz!",
        greatJob: "Great job ",
        wellDone: "Well done ",
        youHave: "You have ",
        from: " from ",
        anweredQuestions: " questions solved correctly ",
        anwerdQuestionsPerfect: " questions solved correctly, great!",
        answeredQuestionsNotBad: " questions solved correctly, not bad!",
        needToTrain: ", you still need to practice a bit!",
        talkWithNutritionist: ", you are welcome to discuss your uncertainties with our nutritionist!",
        errorSpeechFailedCorrectAnswer: "Speech failed on correct answer",
        errorCallEventFailedCorrectAnswer: "Call event failed with correct answer",
        errorSpeechFailedWrongAnswer: "Speech failed on wrong answer",
        errorCallEventFailedWrongAnswer: "Call event failed with wrong answer",
        errorSpeechFailedAtEnd: "Speech failed at the end",
        errorAddingDatasetToHighscoreWhenExisting: "Adding dataset to highscore failed (If other datasets exist).",
        errorAddingDatasetToHighscore: "Adding dataset to highscore failed (if other datasets not present)",
        enterName: "Please enter your name in the field below",
        enterValidName: "Please enter a valid name",
        resultForAge: "Result for age '",
        andModule: "' and module '",
        average: "Average: ",
        median: "Median: ",
        notAvailable: "Not available"
    }
}